"""empty message

Revision ID: 045dcc154d37
Revises: d3c49056f55c
Create Date: 2020-05-19 13:28:35.078063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045dcc154d37'
down_revision = 'd3c49056f55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###
