"""empty message

Revision ID: 12211dd0cbae
Revises: 2219aea1140c
Create Date: 2020-05-27 16:51:01.179710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12211dd0cbae'
down_revision = '2219aea1140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
