"""empty message

Revision ID: 6017e6dd8358
Revises: 046e7bfcbd5c
Create Date: 2020-05-18 00:00:15.834682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6017e6dd8358'
down_revision = '046e7bfcbd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR(length=120)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
