"""empty message

Revision ID: 7e90d0bbf1a3
Revises: 045dcc154d37
Create Date: 2020-05-19 15:33:06.188242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e90d0bbf1a3'
down_revision = '045dcc154d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'date')
    # ### end Alembic commands ###
